// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/bootstrapper/1.0.0-rc.1.0.1/dist/aurelia-bootstrapper.d.ts
declare module '~aurelia-bootstrapper/dist/aurelia-bootstrapper' {
import 'aurelia-polyfills';
import {
  PLATFORM
} from 'aurelia-pal';
import {
  initialize
} from 'aurelia-pal-browser';

/**
 * Manually bootstraps an application.
 * @param configure A callback which passes an Aurelia instance to the developer to manually configure and start up the app.
 * @return A Promise that completes when configuration is done.
 */
export function bootstrap(configure: Function): Promise<void>;
}
declare module 'aurelia-bootstrapper/dist/aurelia-bootstrapper' {
export * from '~aurelia-bootstrapper/dist/aurelia-bootstrapper';
}
declare module 'aurelia-bootstrapper' {
export * from '~aurelia-bootstrapper/dist/aurelia-bootstrapper';
}
