// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/polyfills/1.0.0-rc.1.0.0/dist/aurelia-polyfills.d.ts
declare module '~aurelia-polyfills/dist/aurelia-polyfills' {
import {
  PLATFORM
} from 'aurelia-pal';
}
