
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Property was generated by Visaul Studio settings designer which placed a message in the code file not to alter it.", Scope = "member", Target = "~P:LASI.App.Properties.Settings.Default")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", Justification = "The TrayIconManager instance is captured by a closure in its own constructor.", MessageId = "LASI.App.TrayIconManager+TrayIconProvider", Scope = "member", Target = "LASI.App.TrayIconManager.#Enable(LASI.App.InProgressWindow)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", Justification = "The TrayIconManager instance is captured by a closure in its own constructor.", MessageId = "LASI.App.TrayIconManager+TrayIconProvider", Scope = "member", Target = "LASI.App.TrayIconManager.#Enable(System.Windows.Window)")]

