/// <autosync enabled="true" />
/// <reference path="modernizr-2.8.3.js" />
/// <reference path="bootstrap.js" />
/// <reference path="context.js" />
/// <reference path="jquery-2.1.1.js" />
/// <reference path="jquery-ui.min-1.11.1.js" />
/// <reference path="jquery-ui.unobtrusive-2.2.0.js" />
/// <reference path="jquery.signalr-2.1.2.js" />
/// <reference path="jquery.unobtrusive-ajax.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="knockout-3.0.0.js" />
/// <reference path="require.js" />
/*<reference path="jquery.validate.js" />
/ <reference path="jquery.validate.unobtrusive.js" />
/ <reference path="app/todo.datacontext.js" />
/ <reference path="app/todo.viewmodel.js" />*/
