
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Avoid any cosmetic changes to this class.", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.ParseViaTaggingMode~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Avoid any cosmetic changes to this class.", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.ProcessFileAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Avoid any cosmetic changes to this class.", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.ParseViaTaggingModeAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Avoid any cosmetic changes to this class.", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.ParseViaTaggingModeAsync(TaggerInterop.TaggerMode)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", Justification = "Word exists in domain terminology", MessageId = "Tagset", Scope = "member", Target = "LASI.Content.Tagging.UnknownWordTagException.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "The name text is used in a domain specific context.", MessageId = "LASI.Content.Tagging.TextNode.#ctor(System.String)", Scope = "member", Target = "LASI.Content.Tagging.PhraseExtractor.#ExtractAndConsume(System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "The name text is used in a domain specific context.", MessageId = "LASI.Content.TaggedText.#ctor(System.String,System.String)", Scope = "member", Target = "LASI.Content.Tagging.PhraseExtractor.#ExtractAndConsume(System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.IdentifyCoreferents(System.String[])~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.Similarity~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.Tokenize~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.POSTag~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.Gender~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:LASI.Content.PdfToTextConverter.PdfParser.ExtractText(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.Parse~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.NameFind~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0135:Function does not reach its end or a 'return' statement by any of possible execution paths", Justification = "False postive: single expression", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.ParseViaTaggingModeAsync(TaggerInterop.TaggerMode)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~P:LASI.Content.Tagging.PhraseTagsetMap.Item(LASI.Core.Phrase)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0029:Use coalesce expression", Justification = "<Pending>", Scope = "member", Target = "~M:TaggerInterop.SharpNLPTagger.#ctor(TaggerInterop.TaggerMode,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "API semantics are divergent over a helpful but broad base.", Scope = "member", Target = "~P:LASI.Content.Tagging.WordTagsetMap.Item(LASI.Core.Word)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UnmappedPhraseTypeException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UndelimitedPhraseException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UnknownPartOfSpeechException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UntaggedPhraseException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UntaggedWordException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1194:Implement exception constructors.", Justification = "Exception class is sealed and should not be extended outside of its assembly. Inside said assembly, it does not need these additional constructors.", Scope = "type", Target = "~T:LASI.Content.Tagging.UnmappedWordTypeException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "This warning is false. The parameter is indeed used. It provides the initializing value for the corresponding readonly property. This appears to arise from a code analysis bug. It is only triggered with expression-bodied constructors.", Scope = "member", Target = "~M:LASI.Content.Tagging.TextNode.#ctor(System.String)")]

