using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="CharacterExtensionsTest.IsConsonant.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class CharacterExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant98()
{
    bool b;
    b = this.IsConsonant(' ');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant895()
{
    bool b;
    b = this.IsConsonant('`');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant40()
{
    bool b;
    b = this.IsConsonant('A');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant955()
{
    bool b;
    b = this.IsConsonant('|');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant11()
{
    bool b;
    b = this.IsConsonant('a');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsConsonant66()
{
    bool b;
    b = this.IsConsonant('Y');
    Assert.AreEqual<bool>(true, b);
}
    }
}
