using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="CharacterExtensionsTest.IsAlphabetic.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class CharacterExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsAlphabetic98()
{
    bool b;
    b = this.IsAlphabetic(' ');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsAlphabetic895()
{
    bool b;
    b = this.IsAlphabetic('`');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsAlphabetic305()
{
    bool b;
    b = this.IsAlphabetic('{');
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void IsAlphabetic725()
{
    bool b;
    b = this.IsAlphabetic('a');
    Assert.AreEqual<bool>(true, b);
}
    }
}
