using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="CharacterExtensionsTest.ToUpper.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class CharacterExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CharacterExtensionsTest))]
public void ToUpper88()
{
    char c;
    c = this.ToUpper(' ');
    Assert.AreEqual<char>(' ', c);
}
    }
}
