using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
// <copyright file="EnumerableExtensionsTest.Append.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class EnumerableExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(EnumerableExtensionsTest))]
public void Append61()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.Append<int>((IEnumerable<int>)null, 0);
    Assert.IsNotNull((object)iEnumerable);
}
    }
}
