using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
// <copyright file="EnumerableExtensionsTest.EmptyIfNull.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class EnumerableExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(EnumerableExtensionsTest))]
public void EmptyIfNull352()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(EnumerableExtensionsTest))]
public void EmptyIfNull697()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)ints);
    Assert.IsNotNull((object)iEnumerable);
}
    }
}
