using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="PairTest.Create.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class PairTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PairTest))]
public void Create37()
{
    Pair<int, int> pair;
    pair = this.Create<int, int>(0, 0);
    Assert.AreEqual<int>(0, pair.First);
    Assert.AreEqual<int>(0, pair.Second);
}
    }
}
