using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="StringExtensionsTest.IsNullOrWhiteSpace.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LASI.Utilities
{
    public partial class StringExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace833()
{
    bool b;
    b = this.IsNullOrWhiteSpace("");
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace28()
{
    bool b;
    b = this.IsNullOrWhiteSpace("\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace513()
{
    bool b;
    b = this.IsNullOrWhiteSpace("\u0100");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace906()
{
    bool b;
    b = this.IsNullOrWhiteSpace("\u0100\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace152()
{
    bool b;
    b = this.IsNullOrWhiteSpace("\u0100\u0100");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace919()
{
    bool b;
    b = this.IsNullOrWhiteSpace("\u0100\u0100\0\0");
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void IsNullOrWhiteSpace72()
{
    bool b;
    b = this.IsNullOrWhiteSpace((string)null);
    Assert.AreEqual<bool>(true, b);
}
    }
}
