
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language", "CSE0003:Use expression-bodied members", Justification = "Retaining inline comments.", Scope = "member", Target = "~M:LASI.Core.Lexicon.IsSimilarTo(LASI.Core.Verb,LASI.Core.VerbPhrase)~LASI.Core.Similarity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Justification = "Parameter is a generic delegate whose type parameters are used in the method body." , Scope = "type", Target = "LASI.Core.Analysis.BinderImplementations.Experimental.SequentialPatterns.ActionBindingHelper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.Analysis.PatternMatching.LexicalSpecific.Experimental.FromSpec.ExactTextPredicate<LASI.Core.ILexical>.op_Implicit(System.String)",Justification ="the parameter name is well designated by the name text and is not to be localized.", Scope = "member", Target = "LASI.Core.Analysis.PatternMatching.LexicalSpecific.Experimental.FromSpec.PredicateBuilder.#Test(LASI.Core.ILexical)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.ResourceLoadEventArgs.#ctor(System.String,System.Double)", Scope = "member", Target = "LASI.Core.Lexicon.#LazyLoad`1(LASI.Core.Heuristics.WordNet.WordNetLookup`1<!!0>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.ResourceLoadEventArgs.#ctor(System.String,System.Double)", Scope = "member", Target = "LASI.Core.Heuristics.WordNet.VerbLookup.#Load()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Utilities.Validation.Validate.NotLessThan<System.Int32>(T,T,System.String,System.String)", Scope = "member", Target = "LASI.Core.Document.#Paginate(System.Int32,System.Int32,System.Func`2<System.String,System.Double>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.Analysis.PatternMatching.LexicalSpecific.Experimental.FromSpec.PredicateBuilder.Text(System.String)", Scope = "member", Target = "LASI.Core.Analysis.PatternMatching.LexicalSpecific.Experimental.FromSpec.PredicateBuilder.#Test(LASI.Core.ILexical)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.ResourceLoadEventArgs.#ctor(System.String,System.Double)", Scope = "member", Target = "LASI.Core.Lexicon.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Utilities.Validation.Validate.NotLessThan<System.Int32>(T,T,System.String,System.String)", Scope = "member", Target = "LASI.Core.Symbol.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Core.ResourceLoadEventArgs.#ctor(System.String,System.Double)", Scope = "member", Target = "LASI.Core.Heuristics.WordNet.NounLookup.#Load()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "LASI.Utilities.Validation.Validate.NotEmpty<System.Char>(System.Collections.Generic.IEnumerable<T>,System.String,System.String)", Scope = "member", Target = "LASI.Core.Word.#.ctor(System.String)")]

