#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// Alias types to shorten name and thus file size.

using E = LASI.Core.IEntity;
using V = LASI.Core.IVerbal;
using C = LASI.Core.IConjunctive;
using D = LASI.Core.IDescriptor;
using R = LASI.Core.IReferencer;
using A = LASI.Core.IAdverbial;
using P = LASI.Core.IPrepositional;
using S = LASI.Core.SymbolPhrase;
namespace LASI.Core.Analysis.BinderImplementations.Experimental.SequentialPatterns
{

    using Ae = Action<E>;
    using Av = Action<V>;
    using Ac = Action<C>;
    using Ad = Action<D>;
    using Ar = Action<R>;
    using Aa = Action<A>;
    using Ap = Action<P>;
    using As = Action<S>;
    public partial class BinderComponent :
        IBinderComponent<E, V, C, D, R, A, P>, IBinderComponent<P, E, V, C, D, R, A>, IBinderComponent<A, P, E, V, C, D, R>, IBinderComponent<R, A, P, E, V, C, D>, IBinderComponent<D, R, A, P, E, V, C>, IBinderComponent<R, D, C, A, P, E, V>, IBinderComponent<V, C, D, R, A, P, E>, IBinderComponent<E, R, D, R, A, P, E>, IBinderComponent<E, C, R, E, A, V, E>, IBinderComponent<E, C, E, V, C, V, A>, IBinderComponent<E, E, C, E, C, E, V>, IBinderComponent<S, V, C, D, R, A, P>, IBinderComponent<P, S, V, C, D, R, A>, IBinderComponent<A, P, S, V, C, D, R>, IBinderComponent<R, A, P, S, V, C, D>, IBinderComponent<D, R, A, P, S, V, C>, IBinderComponent<R, D, C, A, S, E, V>, IBinderComponent<V, C, D, R, A, S, E>, IBinderComponent<E, R, D, R, A, P, S>, IBinderComponent<S, C, R, E, A, V, E>, IBinderComponent<E, S, E, V, C, V, A>, IBinderComponent<E, S, C, E, C, E, V>, System.Collections.IEnumerable
    {
        public BinderComponent Match5(Func<A, Func<A, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<C, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<C, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<V, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<V, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<E, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<V, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<E, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<R, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<R, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<R, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<R, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<V, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<A, Func<R, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<P, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<P, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<A, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<C, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<C, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<R, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<A, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<R, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<R, Func<C, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<R, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<A, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<C, Func<A, Func<E, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<E, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<C, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<E, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<E, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<P, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<E, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<A, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<P, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<A, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<A, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<C, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<D, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<A, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<P, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<D, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<P, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<D, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<E, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<C, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<P, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<P, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<E, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<C, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<D, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<A, Func<V, Func<D, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<V, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<C, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<V, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<C, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<C, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<D, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<D, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<D, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<P, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<D, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<V, Func<P, Func<E, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<E, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<P, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<E, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<A, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<C, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<P, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<P, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<A, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<P, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<E, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<E, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<P, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<R, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<D, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<R, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<D, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<E, Func<D, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<R, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<D, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<E, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<A, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<A, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<R, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<E, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<P, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<V, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<R, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<P, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<R, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<V, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<D, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<A, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<D, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<D, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<A, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<E, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<D, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<E, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<A, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<E, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<R, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<E, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<R, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<R, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<E, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<A, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<E, Func<E, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<A, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<A, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<C, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<V, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<S, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<S, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<D, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<S, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<D, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<D, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<D, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<P, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<P, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<D, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<S, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<P, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<V, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<P, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<V, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<V, Func<P, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<C, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<C, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<C, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<P, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<C, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<P, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<S, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<C, Func<A, Func<S, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<D, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<S, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<C, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<D, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<S, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<S, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<S, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<A, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<C, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<P, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<P, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<S, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<P, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<S, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<S, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<S, Func<R, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<D, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<D, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<S, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<D, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<A, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<D, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<A, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<S, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<P, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<S, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<P, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<S, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<P, Func<R, Ad>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<P, Func<C, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<P, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<S, Ap>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<C, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<R, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<R, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<R, Func<C, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<S, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<C, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<S, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<A, Func<D, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<D, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<D, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<S, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<R, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<V, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<A, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<S, Func<E, Ar>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<S, Func<R, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<S, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<R, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<S, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<S, Func<R, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<A, Func<E, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<R, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<R, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<A, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<E, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<A, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<E, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<E, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<E, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<E, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<S, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<E, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<E, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<A, Aa>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<V, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<V, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<E, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<V, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<S, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<A, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<V, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<C, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<E, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<C, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<V, Av>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<E, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, As>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<S, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<V, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<C, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<S, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<E, Ac>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<C, Ae>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
    }
}
#pragma warning restore 1591