#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// Alias types to shorten name and thus file size.

using E = LASI.Core.IEntity;
using V = LASI.Core.IVerbal;
using C = LASI.Core.IConjunctive;
using D = LASI.Core.IDescriptor;
using R = LASI.Core.IReferencer;
using A = LASI.Core.IAdverbial;
using P = LASI.Core.IPrepositional;
using S = LASI.Core.SymbolPhrase;
namespace LASI.Core.Analysis.BinderImplementations.Experimental.SequentialPatterns
{

    using AE = Action<E>;
    using AV = Action<V>;
    using AC = Action<C>;
    using AD = Action<D>;
    using AR = Action<R>;
    using AA = Action<A>;
    using AP = Action<P>;
    using AS = Action<S>;
    public partial class BinderComponent :
        IBinderComponent<E, V, C, D, R, A, P>, IBinderComponent<P, E, V, C, D, R, A>, IBinderComponent<A, P, E, V, C, D, R>, IBinderComponent<R, A, P, E, V, C, D>, IBinderComponent<D, R, A, P, E, V, C>, IBinderComponent<R, D, C, A, P, E, V>, IBinderComponent<V, C, D, R, A, P, E>, IBinderComponent<E, R, D, R, A, P, E>, IBinderComponent<E, C, R, E, A, V, E>, IBinderComponent<E, C, E, V, C, V, A>, IBinderComponent<E, E, C, E, C, E, V>, IBinderComponent<S, V, C, D, R, A, P>, IBinderComponent<P, S, V, C, D, R, A>, IBinderComponent<A, P, S, V, C, D, R>, IBinderComponent<R, A, P, S, V, C, D>, IBinderComponent<D, R, A, P, S, V, C>, IBinderComponent<R, D, C, A, S, E, V>, IBinderComponent<V, C, D, R, A, S, E>, IBinderComponent<E, R, D, R, A, P, S>, IBinderComponent<S, C, R, E, A, V, E>, IBinderComponent<E, S, E, V, C, V, A>, IBinderComponent<E, S, C, E, C, E, V>, System.Collections.IEnumerable
    {
        public BinderComponent Match5(Func<A, Func<A, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<C, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<C, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<V, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<D, Func<P, Func<V, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<E, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<C, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<V, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<E, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<R, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<R, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<D, Func<R, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<R, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<V, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<A, Func<R, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<D, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<P, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<P, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<A, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<C, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<C, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<P, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<D, Func<R, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<A, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<D, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<R, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<R, Func<C, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<R, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<A, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<C, Func<A, Func<E, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<E, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<C, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<E, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<E, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<P, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<E, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<A, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<P, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<A, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<A, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<C, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<D, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<A, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<E, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<P, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<D, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<V, Func<R, Func<P, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<D, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<E, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<V, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<C, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<P, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<P, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<E, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<V, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<C, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<D, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<R, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<A, Func<V, Func<D, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<E, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<V, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<C, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<V, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<C, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<D, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<C, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<D, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<D, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<D, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<E, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<P, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<D, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<E, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<V, Func<P, Func<E, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<E, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<P, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<V, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<E, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<A, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<C, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<P, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<A, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<D, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<E, Func<P, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<A, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<P, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<P, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<E, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<E, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<P, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<R, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<D, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<R, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<D, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<E, Func<D, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<R, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<P, Func<C, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<D, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<E, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<A, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<A, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<C, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<R, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<V, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<E, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<R, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<P, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<E, Func<D, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<E, Func<P, Func<V, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<R, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<A, Func<V, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<P, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<R, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<V, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<V, Func<D, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<A, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<D, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<D, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<A, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<E, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<E, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<D, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<D, Func<E, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<A, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<E, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<R, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<R, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<R, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<D, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<P, Func<R, Func<E, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<R, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<E, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<R, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<R, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<E, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<A, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<A, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<R, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<E, Func<E, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<C, Func<A, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<C, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<C, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<A, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<C, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<C, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<V, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<S, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<S, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<D, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<S, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<V, Func<S, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<D, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<D, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<D, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<P, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<P, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<D, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<V, Func<S, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<P, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<V, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<P, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<P, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<P, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<V, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<V, Func<P, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<S, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<D, Func<C, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<C, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<S, Func<C, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<V, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<C, Func<A, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<P, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<C, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<R, Func<S, Func<P, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<S, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<C, Func<A, Func<S, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<D, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<R, Func<S, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<C, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<S, Func<D, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<S, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<A, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<P, Func<C, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<P, Func<A, Func<S, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<A, Func<S, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<V, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<P, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<A, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<P, Func<P, Func<S, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<C, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<S, Func<P, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<P, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<P, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<V, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<S, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<P, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<A, Func<P, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<V, Func<S, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<V, Func<S, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<S, Func<R, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<D, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<D, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<S, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<C, Func<A, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<D, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<C, Func<A, Func<V, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<A, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<D, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<R, Func<D, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<R, Func<S, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<D, Func<A, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<S, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<P, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<P, Func<R, Func<S, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<P, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<A, Func<S, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<P, Func<R, AD>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<P, Func<C, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<V, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<P, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<R, Func<S, AP>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<C, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<R, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<D, Func<R, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<D, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<R, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<R, Func<C, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<S, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<A, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<A, Func<D, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<D, Func<C, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<S, Func<A, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<R, Func<R, Func<C, Func<S, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<D, Func<S, Func<A, Func<D, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<D, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<D, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<D, Func<S, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<R, Func<C, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<R, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<V, Func<S, Func<C, Func<V, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<S, Func<C, Func<A, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<R, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<S, Func<E, AR>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<R, Func<S, Func<R, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<R, Func<S, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<R, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<A, Func<C, Func<S, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<S, Func<R, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<A, Func<E, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<R, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<R, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<A, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<C, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<A, Func<E, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<A, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<A, Func<E, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<E, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<R, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<E, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<E, Func<E, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<S, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<E, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<V, Func<C, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<E, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<E, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<E, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<E, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<A, AA>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<E, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<C, Func<V, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<V, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<V, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<E, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<A, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<E, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<V, Func<S, Func<V, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<S, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<A, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<V, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<V, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<V, Func<S, Func<C, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<E, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<S, Func<C, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<S, Func<E, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<S, Func<V, AV>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<S, Func<C, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<S, Func<C, Func<E, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<C, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<E, AS>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<E, Func<E, Func<V, Func<S, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<V, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<C, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<C, Func<E, Func<S, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<E, AC>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
        public BinderComponent Match5(Func<C, Func<E, Func<S, Func<C, AE>>>> p) { return Update(p.TryApply(Vals.FindAll(CheckRules).Take(5)), 5); }
    }
}
#pragma warning restore 1591